apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  hostPath:
    path: /data/mongo
    type: DirectoryOrCreate
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
data:
  mongopassword: Y2hhbmRyYQ== #echo -n "chandra" | base64
  mongouser: YWRtaW51c2Vy #echo -n "adminuser" | base64
kind: Secret
metadata:
  name: mongo-init-creds
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP # no need to reach from outside
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        args: ["--dbpath", "/data/db"]
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data-dir
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongouser
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongopassword
      volumes:
      - name: mongo-data-dir
        persistentVolumeClaim:
          claimName: "mongo-pvc"
  selector:
    matchLabels:
      app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: middleware
spec:
  selector:
    app: middleware
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
    nodePort: 30007
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: cbagade/middleware:v8
        env:
        - name: MONGO_ADDRESS
          value: "mongodb.kube-learnings" # mongo db service + . + namespace
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongouser
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongopassword
  selector:
    matchLabels:
      app: middleware


# kubectl apply -f app_deployment.yaml
# kubectl get pods -w  (wait for pods to be in running state)
# GET app_2 /api/v1/fruits change port to 30001
# POST  app_2/api/v1/fruits change port to 30001
# Verify the changes
# GET  app_2/api/v1/fruits change port to 30001

# kubectl delete -f app_deployment.yaml
# kubectl apply -f app_deployment.yaml
# GET app_2/api/v1/fruits change port to 30001
# changes persisted
